"""Added modules

Revision ID: 191852c82ed6
Revises: f564287fcc02
Create Date: 2023-04-09 13:11:08.854611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "191852c82ed6"
down_revision = "f564287fcc02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "module",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_module_id"), "module", ["id"], unique=False)
    op.add_column(
        "courses", sa.Column("module_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "courses", "module", ["module_id"], ["id"])
    op.add_column("users", sa.Column("module_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "module", ["module_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "module_id")
    op.drop_constraint(None, "courses", type_="foreignkey")
    op.drop_column("courses", "module_id")
    op.drop_index(op.f("ix_module_id"), table_name="module")
    op.drop_table("module")
    # ### end Alembic commands ###
